[package]
authors = ["Hoon Wee <mrgravity817@gmail.com>"]
edition = "2021"
name = "z2p"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "z2p"
path = "src/main.rs"

[dependencies]
actix-web = "4"
serde = {version = "1", features = ["derive"]}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}

[dev-dependencies]
reqwest = "0.11"
